const contractAddress = "0xc3151009eD58b88a3f02235B8040Acd3DbaB45dD"; // Replace with your own contract address
const chain = 'polygon'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Galaxy Bunny NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Galaxy Bunny NFT Project is a decentralized, open-source project. ';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "We do not run a pre-sale! Please wait for the public sale!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "Please wait for the public sale.";
const p_presale_mint_whitelisted = "Please wait for the public sale";
const p_presale_mint_already_minted = "Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open!";
const button_presale_coming_soon = "No Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "No Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. Please try again.";
